In [1]:
import json
import pandas as pd

In [2]:
# data = json.load(open('./temp.results.json', 'r'))
# data_muse = json.load(open('./temp.results.muse-small-v3.json', 'r'))
data_teacher = json.load(open('./temp.results.model-teachers.json', 'r'))

# data_mlqa_non_en = json.load(open('./temp.results.mlqa-dataset-non-en.json', 'r'))

In [4]:
list(data_teacher.keys()), len(list(data_teacher.keys()))

(['dataset-xquad_en_train',
  'dataset-xorqa_bn_train',
  'dataset-xorqa_bn_val',
  'dataset-xorqa_ja_train',
  'dataset-xorqa_ja_val',
  'dataset-xorqa_ko_train',
  'dataset-xorqa_ko_val',
  'dataset-xorqa_ru_train',
  'dataset-xorqa_ru_val',
  'dataset-xorqa_fi_train',
  'dataset-xorqa_fi_val',
  'dataset-xorqa_ar_train',
  'dataset-xorqa_te_train',
  'dataset-xorqa_te_val',
  'dataset-xorqa_ar_val',
  'dataset-mlqa_en_val',
  'dataset-mlqa_en_test',
  'dataset-mlqa_ar_val',
  'dataset-mlqa_ar_test',
  'dataset-mlqa_de_val',
  'dataset-mlqa_de_test',
  'dataset-mlqa_es_val',
  'dataset-mlqa_es_test',
  'dataset-mlqa_hi_val',
  'dataset-mlqa_hi_test',
  'dataset-mlqa_vi_val',
  'dataset-mlqa_vi_test',
  'dataset-mlqa_zh_val',
  'dataset-mlqa_zh_test'],
 29)

In [ ]:
list(data['dataset-xquad_en_train'].keys()), len(list(data['dataset-xquad_en_train'].keys()))

In [ ]:
17*6

In [5]:
result_obj = []
for dataset_name, result_model_group in data_teacher.items():
#     print(dataset_name)
    for model_name, (metric, raw_result) in result_model_group.items():
#         print(model_name)
        top1, precision_at_k = metric
        
#         print(len(metric))
#         print(metric)
        result_obj.append({
            'dataset_name': dataset_name,
            'model_name': model_name,
            'precision_at_1': top1,
            'precision_at_2': precision_at_k['2'],
            'precision_at_3': precision_at_k['6'],
            'precision_at_4': precision_at_k['4'],
            'precision_at_5': precision_at_k['5'],
            'precision_at_10': precision_at_k['10'],
        })
    
df = pd.DataFrame.from_dict(result_obj)

# df.to_csv('./online_prompt_eval.8-5-2022.csv')
df.to_csv('./online_prompt_eval-teacher.11-5-2022.csv')

In [6]:
# result_obj = []
# for dataset_name, result_model_group in data_mlqa_non_en.items():
# #     print(dataset_name)
#     for model_name, (metric, raw_result) in result_model_group.items():
# #         print(model_name)
#         top1, precision_at_k = metric
        
# #         print(len(metric))
# #         print(metric)
#         result_obj.append({
#             'dataset_name': dataset_name,
#             'model_name': model_name,
#             'precision_at_1': top1,
#             'precision_at_2': precision_at_k['2'],
#             'precision_at_3': precision_at_k['6'],
#             'precision_at_4': precision_at_k['4'],
#             'precision_at_5': precision_at_k['5'],
#             'precision_at_10': precision_at_k['10'],
#         })
    
# df = pd.DataFrame.from_dict(result_obj)

# # df.to_csv('./online_prompt_eval.8-5-2022.csv')
# df.to_csv('./online_prompt_eval-mlqa_non_en.11-5-2022.csv')

In [15]:
# result_obj = []
# for dataset_name, result_model_group in data.items():
# #     print(dataset_name)
#     for model_name, (metric, raw_result) in result_model_group.items():
# #         print(model_name)
#         top1, precision_at_k = metric
        
# #         print(len(metric))
# #         print(metric)
#         result_obj.append({
#             'dataset_name': dataset_name,
#             'model_name': model_name,
#             'precision_at_1': top1,
#             'precision_at_2': precision_at_k['2'],
#             'precision_at_3': precision_at_k['6'],
#             'precision_at_4': precision_at_k['4'],
#             'precision_at_5': precision_at_k['5'],
#             'precision_at_10': precision_at_k['10'],
#         })
    
#     muse_model_name = 'model-muse_small_v3'
#     (muse_metric, muse_raw_result) = data_muse[dataset_name][muse_model_name]
#     top1, precision_at_k = muse_metric

#     result_obj.append({
#             'dataset_name': dataset_name,
#             'model_name': muse_model_name,
#             'precision_at_1': top1,
#             'precision_at_2': precision_at_k['2'],
#             'precision_at_3': precision_at_k['6'],
#             'precision_at_4': precision_at_k['4'],
#             'precision_at_5': precision_at_k['5'],
#             'precision_at_10': precision_at_k['10'],
#         })

In [16]:
df = pd.DataFrame.from_dict(result_obj)

In [17]:
df

,dataset_name,model_name,precision_at_1,precision_at_2,precision_at_3,precision_at_4,precision_at_5,precision_at_10
0,dataset-xquad_en_train,model-xquad_student_supported_langs,0.468067,0.668067,0.981513,0.899160,0.945378,0.998319
1,dataset-xquad_en_train,model-xorqa_student_supported_langs,0.712605,0.851261,0.990756,0.968067,0.986555,0.997479
2,dataset-xquad_en_train,model-mlqa_student_supported_langs,0.737815,0.884034,0.993277,0.978992,0.989076,0.997479
3,dataset-xquad_en_train,model-xquad_student_unsupported_langs,0.401681,0.621008,0.968067,0.883193,0.940336,0.993277
4,dataset-xquad_en_train,model-xorqa_student_unsupported_langs,0.689076,0.840336,0.993277,0.962185,0.982353,0.997479
...,...,...,...,...,...,...,...,...
114,dataset-xorqa_ar_val,model-mlqa_student_supported_langs,0.540206,0.748454,0.975258,0.931959,0.967010,0.989691
115,dataset-xorqa_ar_val,model-xquad_student_unsupported_langs,0.404124,0.628866,0.956701,0.880412,0.925773,1.000000
116,dataset-xorqa_ar_val,model-xorqa_student_unsupported_langs,0.453608,0.717526,0.975258,0.921649,0.962887,0.985567
117,dataset-xorqa_ar_val,model-mlqa_student_unsupported_langs,0.556701,0.744330,0.979381,0.915464,0.960825,0.987629
118,dataset-xorqa_ar_val,model-muse_small_v3,0.542268,0.758763,0.977320,0.942268,0.969072,0.991753

In [18]:
# df.to_csv('./online_prompt_eval.8-5-2022.csv')
df.to_csv('./online_prompt_eval+muse_small.9-5-2022.csv')

dict_keys(['model-muse_small_v3'])